data:extend(
{ 
    {
    type = "technology",
    name="alien-hybridization1",
    icon = "__AlienWall__/graphics/icons/wall/hybrid-wall.png",
    effects = {{type = "unlock-recipe", recipe="hybridized-wall"}},
    prerequisites = {"alien-fragments", "stone-walls"},
    unit = alien_research(50, 10, 5, 0, 0, 5),
    order="a-e-a",
  },
    {
    type = "technology",
    name="alien-hybridization2",
    icon = "__AlienWall__/graphics/icons/gate/hybrid-gate.png",
    effects = {{type = "unlock-recipe", recipe="hybridized-gate"}},
    prerequisites = {"alien-hybridization1", "gates"},
    unit = alien_research(75, 15, 10, 0, 0, 10),
    order="a-e-b",
  },
  {
    type = "technology",
    name="alien-hybrid-upgrade-1",
    icon = "__AlienWall__/graphics/icons/wall/hybrid-wall.png",
    prerequisites = {"alien-hybridization2"},
    unit = alien_research(75, 15, 10, 0, 0, 10),
    order="a-f-a",
  },
  {
    type = "technology",
    name="alien-hybrid-upgrade-2",
    icon = "__AlienWall__/graphics/icons/wall/hybrid-wall.png",
    prerequisites = {"alien-hybrid-upgrade-1", "endo-skeleton"},
    unit = alien_research(100, 15, 10, 5, 0, 10),
    order="a-f-b",
	upgrade = "true",
  },
  {
    type = "technology",
    name="alien-hybrid-upgrade-3",
    icon = "__AlienWall__/graphics/icons/wall/hybrid-wall.png",
    prerequisites = {"alien-hybrid-upgrade-2", "exo-skeleton"},
    unit = alien_research(100, 15, 15, 10, 5, 10),
    order="a-f-c",
	upgrade = "true",
  },
  {
    type = "technology",
    name="alien-hybrid-upgrade-4",
    icon = "__AlienWall__/graphics/icons/wall/hybrid-wall.png",
    prerequisites = {"alien-hybrid-upgrade-3"},
    unit = alien_research(125, 15, 15, 10, 10, 10),
    order="a-f-c",
	upgrade = "true",
  },
})